language: java
jdk:
  - oraclejdk9
script:
  - mvn clean install -DskipTests
  - mvn test
  #- mvn clean verify -Parquillian-glassfish-embedded
  #- mvn clean verify -Parquillian-glassfish-managed
  - mvn archetype:create-from-project
